name: midip
description: A simple midi player.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  dart_midi: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
